/**
 * Regenerate the specification from the code.
 *
 * **Asked for on 10 September 2026:** *"make sure all of this is documented so
 * when we are architecting the system - every single bit of it is known to the
 * minute feature and detail."*
 *
 * Three of the specification documents already claimed to be generated, and one
 * of them had drifted anyway — the front page said 195 routes while the routes
 * document said 178. A claim nobody re-runs is a claim, not a fact. So this is
 * the one command that produces all of them, and `test/spec.test.ts` fails when
 * what is on disk is not what this would write.
 *
 * Run with:  npm run spec
 *
 * It is driven by Vite rather than node directly, because the registry is
 * TypeScript and the honest way to enumerate the routes is to build the real
 * application and read its router — not to grep for `r.get(`. A regular
 * expression over the source would miss a route registered in a loop and
 * invent one that is commented out.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createServer } from 'vite';
import { refusalsIn } from './spec-refusals.mjs';

const { DatabaseSync } = process.getBuiltinModule('node:sqlite');

// --- the schema, as it finally stands ---------------------------------------
//
// Built by running every migration, never read from the files: a rule later
// replaced still sits in the file that created it, and reading the files
// counted several twice.
function schema() {
  const db = new DatabaseSync(':memory:');
  for (const f of readdirSync('migrations').filter((f) => f.endsWith('.sql')).sort()) {
    db.exec(readFileSync(`migrations/${f}`, 'utf8'));
  }
  return db;
}

const db = schema();
const q = (sql, ...args) => db.prepare(sql).all(...args);

const tables = q(`SELECT name FROM sqlite_master WHERE type='table'
                   AND name NOT LIKE 'sqlite_%' AND name <> 'd1_migrations' ORDER BY name`)
  .map((r) => r.name);

const refusals = q(`SELECT name, tbl_name, sql FROM sqlite_master WHERE type='trigger'`)
  .flatMap((r) => refusalsIn(r.sql).map((x) => ({ table: r.tbl_name, ...x })));

const uniques = q(`SELECT tbl_name, sql FROM sqlite_master
                    WHERE type='index' AND sql LIKE '%UNIQUE%' ORDER BY tbl_name`)
  .map((r) => {
    const m = /ON \w+\s*\(([^)]*)\)(\s*WHERE\s+(.*))?/is.exec(r.sql);
    return { table: r.tbl_name, cols: m ? m[1].replace(/\s+/g, ' ').trim() : '',
             where: m && m[3] ? m[3].trim().replace(/\s+/g, ' ') : '' };
  });

// --- the application, as it is actually mounted -----------------------------
const vite = await createServer({ server: { middlewareMode: true }, appType: 'custom', logLevel: 'error' });
const { createApp } = await vite.ssrLoadModule('/src/app.ts');
const { registeredModules } = await vite.ssrLoadModule('/src/registry.ts');
const { ROLE_PERMISSIONS, PERMISSIONS } = await vite.ssrLoadModule('/src/core/rbac.ts');

const app = createApp();
// Hono's table carries middleware as well as handlers. A handler is a real
// method on a real path; `ALL` and a trailing `*` are the guards.
const seen = new Set();
const routes = [];
for (const r of app.routes) {
  if (r.method === 'ALL' || r.path.endsWith('*')) continue;
  const key = `${r.method} ${r.path}`;
  if (seen.has(key)) continue;
  seen.add(key);
  routes.push({ method: r.method, path: r.path });
}
routes.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));

/** Which module owns a path, by its declared base paths. */
function ownerOf(path) {
  let best = null;
  for (const m of registeredModules) {
    for (const base of m.basePaths ?? []) {
      if (path === base || path.startsWith(base.endsWith('/') ? base : `${base}/`)) {
        if (!best || base.length > best.len) best = { name: m.name, len: base.length };
      }
    }
  }
  return best?.name ?? '—';
}

await vite.close();

mkdirSync('docs/spec', { recursive: true });
const esc = (s) => String(s).replace(/\|/g, '\\|');

// --- features.md ------------------------------------------------------------
{
  const lines = [
    '# The features',
    '',
    `**${registeredModules.length} modules.** Generated by \`npm run spec\` from the registry`,
    'itself, so it lists what is mounted rather than what somebody remembered to',
    'write down.',
    '',
    'A feature here is a folder under `src/modules` exporting one `AppModule`. It',
    'owns its routes, its navigation entry and its settings. Adding one is a folder',
    'and a line in `src/registry.ts`; removing one is deleting that line.',
    '',
    '**The order matters.** Modules are mounted in registry order, and a module that',
    'guards `*` from `/` guards every path registered after it. That is why the two',
    'pages a client opens with no account — `/q` and `/d` — are mounted above the',
    'dashboard, and why a test holds them there.',
    '',
    '| # | Module | What it is | Mounted at | Routes | In the menu |',
    '|---:|---|---|---|---:|---|',
  ];
  registeredModules.forEach((m, i) => {
    const bases = (m.basePaths ?? []).map((b) => `\`${b}\``).join(', ') || '—';
    const count = routes.filter((r) => ownerOf(r.path) === m.name).length;
    const nav = (m.nav ?? []).map((n) => `${n.group ? `${n.group} → ` : ''}${n.label}`).join(', ') || '—';
    lines.push(`| ${i + 1} | \`${m.name}\` | ${esc(m.title)} | ${bases} | ${count} | ${esc(nav)} |`);
  });
  lines.push('', '## What each module owns', '');
  for (const m of registeredModules) {
    lines.push(`### \`${m.name}\` — ${m.title}`, '');
    const mine = routes.filter((r) => ownerOf(r.path) === m.name);
    if (mine.length) {
      lines.push('| | |', '|---|---|');
      for (const r of mine) lines.push(`| ${r.method} | \`${r.path}\` |`);
      lines.push('');
    }
    const groups = m.settings ?? [];
    if (groups.length) {
      lines.push(`Settings: ${groups.map((g) => `**${g.title}** (${g.settings.length} keys)`).join(', ')}`, '');
    }
    if (!mine.length && !groups.length) lines.push('_No routes of its own._', '');
  }
  writeFileSync('docs/spec/features.md', lines.join('\n') + '\n');
  console.log(`features.md    ${registeredModules.length} modules`);
}

// --- settings.md ------------------------------------------------------------
//
// The per-practice knobs. These matter more than they look: the decision of
// 3 September 2026 is that a second practice gets a database of its own, and
// that anything differing between practices lives in settings or a vocabulary
// rather than in the code. This list is therefore the answer to "what can
// differ between two practices without a deployment".
{
  const groups = registeredModules.flatMap((m) => (m.settings ?? []).map((g) => ({ m: m.name, g })));
  groups.sort((a, b) => (a.g.order ?? 999) - (b.g.order ?? 999) || a.g.title.localeCompare(b.g.title));
  const total = groups.reduce((n, x) => n + x.g.settings.length, 0);
  const lines = [
    '# The settings',
    '',
    `**${total} settings in ${groups.length} groups.** Generated by \`npm run spec\`.`,
    '',
    'Everything an administrator can change without a deployment. This is also the',
    'answer to *what may differ between two practices*: the standing decision of',
    '3 September 2026 is that a second practice gets a database of its own, and that',
    'anything differing between practices belongs here or in a vocabulary — because',
    'those already live inside the practice’s own database and so become',
    'per-practice for free.',
    '',
  ];
  for (const { m, g } of groups) {
    lines.push(`## ${g.title}`, '');
    if (g.description) lines.push(esc(g.description), '');
    lines.push(`Owned by \`${m}\`.`, '', '| Key | Type | Default | What it governs |', '|---|---|---|---|');
    for (const s of g.settings) {
      const dflt = s.default === '' || s.default === undefined ? '_blank_' : `\`${esc(String(s.default))}\``;
      lines.push(`| \`${s.key}\` | ${s.type} | ${dflt} | ${esc(s.help ?? s.label ?? '')} |`);
    }
    lines.push('');
  }
  writeFileSync('docs/spec/settings.md', lines.join('\n') + '\n');
  console.log(`settings.md    ${total} settings in ${groups.length} groups`);
}

// --- permissions.md ---------------------------------------------------------
{
  const roles = Object.keys(ROLE_PERMISSIONS);
  const perms = [...PERMISSIONS].sort();
  const byPerm = new Map(perms.map((p) => [p, routes.filter(() => false).length]));
  const lines = [
    '# Permissions and roles',
    '',
    `**${perms.length} permissions across ${roles.length} roles.** Generated by \`npm run spec\`.`,
    '',
    'Access is checked by middleware rather than inside a handler, so a route added',
    'later cannot forget to check. A role is a set of permissions and nothing else —',
    'there is no second place where a role means something.',
    '',
    `| Permission | ${roles.join(' | ')} |`,
    `|---|${roles.map(() => '---').join('|')}|`,
  ];
  for (const p of perms) {
    const cells = roles.map((r) => ((ROLE_PERMISSIONS[r] ?? []).includes(p) ? 'yes' : '·'));
    lines.push(`| \`${p}\` | ${cells.join(' | ')} |`);
  }
  writeFileSync('docs/spec/permissions.md', lines.join('\n') + '\n');
  console.log(`permissions.md ${perms.length} permissions, ${roles.length} roles`);
}

// --- routes.md --------------------------------------------------------------
{
  const lines = [
    '# The routes',
    '',
    `**${routes.length} routes across ${registeredModules.length} modules.** Generated by`,
    '`npm run spec` from the built router, so it cannot drift.',
    '',
    '## How access control works here',
    '',
    'Every route is behind the guard its module registers, and the guard is',
    'middleware rather than a check inside the handler — so a route added later',
    'cannot forget. A module usually registers one guard for everything it owns; a',
    'route needing more says so itself. `docs/spec/permissions.md` has the matrix.',
    '',
    '## The public surface',
    '',
    'The routes reachable with no session at all. This list *is* the public surface',
    'of the register, and it is the one to read before anything else here.',
    '',
    '| | | Owned by |',
    '|---|---|---|',
  ];
  const PUBLIC_MODULES = new Set(['landing', 'auth', 'clientquote', 'publicdoc']);
  const isPublic = (r) => PUBLIC_MODULES.has(ownerOf(r.path)) || r.path === '/healthz'
    || r.path.startsWith('/api/ingest');
  for (const r of routes.filter(isPublic)) {
    lines.push(`| ${r.method} | \`${r.path}\` | ${ownerOf(r.path)} |`);
  }
  lines.push('', '## Every route', '', '| | | Owned by |', '|---|---|---|');
  for (const r of routes) lines.push(`| ${r.method} | \`${r.path}\` | ${ownerOf(r.path)} |`);
  writeFileSync('docs/spec/routes.md', lines.join('\n') + '\n');
  console.log(`routes.md      ${routes.length} routes`);
}

// --- data-model.md ----------------------------------------------------------
{
  const lines = [
    '# The data model',
    '',
    `**${tables.length} tables, every column.** Generated by \`npm run spec\` from a database`,
    'built by running every migration — not from the migration files, because a rule',
    'later replaced still sits in the file that created it.',
    '',
  ];
  for (const t of tables) {
    lines.push(`## \`${t}\``, '', '| Column | Type | Null | Default |', '|---|---|---|---|');
    for (const c of q(`PRAGMA table_info('${t}')`)) {
      lines.push(`| \`${c.name}\`${c.pk ? ' _(pk)_' : ''} | ${c.type || '—'} | `
        + `${c.notnull ? 'no' : 'yes'} | ${c.dflt_value === null ? '—' : `\`${esc(c.dflt_value)}\``} |`);
    }
    lines.push('');
  }
  writeFileSync('docs/spec/data-model.md', lines.join('\n') + '\n');
  console.log(`data-model.md  ${tables.length} tables`);
}

// --- invariants.md ----------------------------------------------------------
{
  const byTable = new Map();
  for (const r of refusals) {
    if (!byTable.has(r.table)) byTable.set(r.table, []);
    byTable.get(r.table).push(r);
  }
  const lines = [
    '# What the database refuses',
    '',
    `**${refusals.length} refusals** across ${byTable.size} tables, plus`,
    `${uniques.length} uniqueness rules. Generated by \`npm run spec\`.`,
    '',
    'The standing decision this document exists for: *invariants belong in the',
    'database, as triggers and constraints, not in the route that happens to write',
    'the row.* A guarantee in a handler lasts until somebody adds a second handler —',
    'and this register is written to by the application, by bulk loads, and',
    'occasionally by hand.',
    '',
    '## How to test one',
    '',
    'By attacking the database directly, never through the application. A test that',
    'goes through a route proves the route is careful; the point of putting the rule',
    'here is that it holds when the route is not.',
    '',
    '## The refusals, by table',
    '',
  ];
  for (const t of [...byTable.keys()].sort()) {
    lines.push(`### \`${t}\``, '', '| On | The database refuses |', '|---|---|');
    const rows = byTable.get(t)
      .map((r) => `| ${r.when} | ${esc(r.text)} |`)
      .sort();
    lines.push(...rows, '');
  }
  lines.push('## Uniqueness', '', '| Table | Columns | Only where |', '|---|---|---|');
  for (const u of uniques) {
    lines.push(`| \`${u.table}\` | \`${esc(u.cols)}\` | ${u.where ? `\`${esc(u.where)}\`` : 'always'} |`);
  }
  writeFileSync('docs/spec/invariants.md', lines.join('\n') + '\n');
  console.log(`invariants.md  ${refusals.length} refusals, ${uniques.length} uniqueness rules`);
}
